### ISSUE TITLE
how value of currentRequestindex changes when we update the data in firestore. 

### ISSUE THREAD

**Issue by insomniacdartcode** [topG20xx/streamfirestorepagination#1]
complete fetchcommentlist executed or not?

**Comment by deeprajsinghsisodiya** [comment]
currentRequestIndex is working like cursor.

When you update the firestore, only the syntax in 'listen' is executed.
var pageExists = currentRequestIndex < _comments.length;
That means, this syntax return true when you update firestore.

var currentRequestIndex = _comments.length;
Because, this syntax is outside of 'listen', so it contains value before you updated.
